reset_all_meters:
  name: Reset all meters
  description: Reset all dynamic energy meters to 0.

reset_selected_meters:
  name: Reset selected meters
  description: Reset only the specified entity_ids to 0.
  fields:
    entity_ids:
      name: Entity IDs
      description: List of sensor entity_ids to reset.
      required: true
      example: ["sensor.dynamic_energy_calculator_kwh_total"]

set_meter_value:
  name: Set meter value
  description: Manually set the value of a meter.
  fields:
    entity_id:
      name: Entity ID
      description: The entity_id of the sensor.
      required: true
      example: "sensor.dynamic_energy_calculator_kwh_total"
    value:
      name: Value
      description: The new value for the sensor.
      required: true
      example: 123.45
