name: Release Versioning

on:
  # Trigger on push of a tag vX.Y.Z
  push:
    tags:
      - 'v*.*.*'
  # Trigger when a Release is published via the GitHub UI
  release:
    types: [published]

jobs:
  bump-release:
    # Ensure that only this job handles the tag push
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump version in manifest.json
        # Use --no-tag so we only bump the file for the release
        run: bump2version patch --allow-dirty --no-tag

      - name: Commit & Push bumped files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add custom_components/dynamic_energy_calculator/manifest.json
          git commit -m "chore: bump to next version after release ${{ github.ref_name }}"
          git push origin HEAD:main

  publish-release:
    # This job runs after creating the GitHub Release (event 'published')
    if: github.event_name == 'release'
    needs: bump-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release from tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
